### ISSUE TITLE
last step failed jupyter kernelspec install --name ocaml-jupyter "$(opam config var share)/jupyter"

### ISSUE THREAD

**Issue by brando90** [akabe/ocaml-jupyter#132]
error:

```
(base) brandomiranda~ $ jupyter kernelspec install --name ocaml-jupyter "$(opam config var share)/jupyter"
Traceback (most recent call last):
  File "/Users/brandomiranda/anaconda3/bin/jupyter-kernelspec", line 10, in <module>
    sys.exit(KernelSpecApp.launch_instance())
  File "/Users/brandomiranda/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/brandomiranda/anaconda3/lib/python3.7/site-packages/jupyter_client/kernelspecapp.py", line 273, in start
    return self.subapp.start()
  File "/Users/brandomiranda/anaconda3/lib/python3.7/site-packages/jupyter_client/kernelspecapp.py", line 143, in start
    replace=self.replace,
  File "/Users/brandomiranda/anaconda3/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 346, in install_kernel_spec
    shutil.copytree(source_dir, destination)
  File "/Users/brandomiranda/anaconda3/lib/python3.7/shutil.py", line 315, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/brandomiranda/.opam/4.06.0/share/jupyter'
```

**Comment by brando90** [comment]
```
(base) brandomiranda~ $ opam install jupyter-archimedes
The following actions will be performed:
  ∗ install archimedes         0.4.18 [required by jupyter-archimedes]
  ∗ install conf-zmq           0.1    [required by zmq]
  ∗ install conf-cairo         1      [required by cairo2]
  ∗ install zmq                5.0.0  [required by jupyter]
  ∗ install cairo2             0.6    [required by jupyter-archimedes]
  ∗ install zmq-lwt            5.0.0  [required by jupyter]
  ∗ install jupyter            2.6.0  [required by jupyter-archimedes]
  ∗ install jupyter-archimedes 2.3.2
===== ∗ 8 =====
Do you want to continue? [Y/n] Y

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
[archimedes.0.4.18] found in cache
[cairo2.0.6] found in cache
Processing  5/8: [jupyter.2.6.0: dl]
[jupyter-archimedes.2.3.2] found in cache
[zmq.5.0.0] found in cache
[zmq-lwt.5.0.0] found in cache
[jupyter.2.6.0] downloaded from cache at https://opam.ocaml.org/cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
[ERROR] The compilation of conf-cairo failed at "/Users/brandomiranda/.opam/opam-init/hooks/sandbox.sh build sh -exc export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/; pkg-config --libs cairo".
[ERROR] The compilation of conf-zmq failed at "/Users/brandomiranda/.opam/opam-init/hooks/sandbox.sh build cc test.c -I/usr/local/include -L/usr/local/lib -lzmq".
[ERROR] The compilation of archimedes failed at "/Users/brandomiranda/.opam/opam-init/hooks/sandbox.sh build ocaml setup.ml -configure --prefix /Users/brandomiranda/.opam/4.06.0 --enable-graphics".

#=== ERROR while compiling conf-zmq.0.1 =======================================#
# context     2.0.0 | macos/x86_64 | ocaml-base-compiler.4.06.0 | https://opam.ocaml.org#136fdfd4
# path        ~/.opam/4.06.0/.opam-switch/build/conf-zmq.0.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build cc test.c -I/usr/local/include -L/usr/local/lib -lzmq
# exit-code   1
# env-file    ~/.opam/log/conf-zmq-43129-736596.env
# output-file ~/.opam/log/conf-zmq-43129-736596.out
### output ###
# test.c:1:10: fatal error: 'zmq.h' file not found
# #include <zmq.h>
#          ^~~~~~~
# 1 error generated.


#=== ERROR while compiling conf-cairo.1 =======================================#
# context     2.0.0 | macos/x86_64 | ocaml-base-compiler.4.06.0 | https://opam.ocaml.org#136fdfd4
# path        ~/.opam/4.06.0/.opam-switch/build/conf-cairo.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build sh -exc export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/; pkg-config --libs cairo
# exit-code   1
# env-file    ~/.opam/log/conf-cairo-43129-0c525f.env
# output-file ~/.opam/log/conf-cairo-43129-0c525f.out
### output ###
# + export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/
# + PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/
# + pkg-config --libs cairo
# Package cairo was not found in the pkg-config search path.
# Perhaps you should add the directory containing `cairo.pc'
# to the PKG_CONFIG_PATH environment variable
# No package 'cairo' found


#=== ERROR while compiling archimedes.0.4.18 ==================================#
# context     2.0.0 | macos/x86_64 | ocaml-base-compiler.4.06.0 | https://opam.ocaml.org#136fdfd4
# path        ~/.opam/4.06.0/.opam-switch/build/archimedes.0.4.18
# command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml setup.ml -configure --prefix /Users/brandomiranda/.opam/4.06.0 --enable-graphics
# exit-code   1
# env-file    ~/.opam/log/archimedes-43129-6aa130.env
# output-file ~/.opam/log/archimedes-43129-6aa130.out
### output ###
# File "setup.ml", line 7667, characters 15-32:
# Warning 3: deprecated: String.capitalize
# Use String.capitalize_ascii instead.
# ocamlfind: Package `camlp4' not found
# W: Field 'pkg_camlp4' is not set: Command ''/Users/brandomiranda/.opam/4.06.0/bin/ocamlfind' query -format %d camlp4 > '/var/folders/vz/9vkmdqbn3ml_12rcbh66rn4c0000gn/T/oasis-dc8343.txt'' terminated with error code 2
# E: Cannot find findlib package camlp4
# E: Failure("1 configuration error")



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
┌─ The following actions failed
│ λ build archimedes 0.4.18
│ λ build conf-cairo 1
│ λ build conf-zmq   0.1
└─
╶─ No changes have been performed

The packages you requested declare the following system dependencies. Please make sure they are installed before retrying:
    cairo zeromq
```

**Comment by akabe** [comment]
The directory `/Users/brandomiranda/.opam/4.06.0/share/jupyter` should be created by opam. You failed installing ocaml-jupyter. Re-install.

zmq and cairo requires external packages. I think you can install them by brew.

**Comment by mseri** [comment]
@brando90 have you installed the c dependencies? `opam depext jupyter-archimedes` should be fine if you use homebrew, otherwise manually install cairo and libzmq. 

Once that is done, everything should work but you may need to use a specific PKG_CONFIG_PATH. This depends on what you use and have installed. For example, on my system I need to do `PKG_CONFIG_PATH=/usr/local/opt/openblas/lib/pkgconfig:/usr/local/Cellar/libffi/3.2.1/lib/pkgconfig opam install ...` for certain packages.

**Comment by paitonic** [comment]
More or less steps I took to install it (Debian):

```
sudo apt-get install libcairo2-dev libgmp-dev libczmq-dev
pip install jupyter
opam install jupyter

# if jupyter-archimeded fails to compile because of cairo - https://github.com/akabe/ocaml-jupyter/issues/118#issuecomment-486981929
opam install "cairo2<0.6"
opam install archimedes  # or reinstall
opam install jupyter-archimedes

# jupyter kernelspec failed after:
jupyter kernelspec install --name ocaml-jupyter "$(opam config var share)/jupyter"
[Errno 13] Permission denied: '/usr/local/share/jupyter'              
Perhaps you want to install with `sudo` or `--user`? 

# this one worked
jupyter kernelspec install --name ocaml-jupyter --user /home/<USER>/.opam/default/share/jupyter
```

**Comment by akabe** [comment]
I added description about --user option in README 3641f9689a0bcabfa7f8982bd13ab154fc1cfbd7.
