### ISSUE TITLE
Failed to start the ocaml-jupyter kernal in jupyter notebook in windows 10

### ISSUE THREAD

**Issue by Hanok-Solomon-Vangepurapu** [akabe/ocaml-jupyter#175]
*******Hey HIi i have installled ocaml 64 and cygwin64 terminal in windows 10 i have complete set the kernal by using this steps https://github.com/akabe/ocaml-jupyter.. but i got kernal error in top right corner in jupyter notebook , i have used ocaml kernal version 4.12.0+ mingw64 can i anyone please help me to fix this error THANKS IN ADVANCE *********

Traceback (most recent call last):
File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\tornado\web.py", line 1704, in _execute
result = await result
File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\tornado\gen.py", line 769, in run
yielded = self.gen.throw(*exc_info) # type: ignore
File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\notebook\services\sessions\handlers.py", line 69, in post
model = yield maybe_future(
File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\tornado\gen.py", line 762, in run
value = future.result()
File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\tornado\gen.py", line 769, in run
yielded = self.gen.throw(*exc_info) # type: ignore
File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 98, in create_session
kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\tornado\gen.py", line 762, in run
value = future.result()
File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\tornado\gen.py", line 769, in run
yielded = self.gen.throw(*exc_info) # type: ignore
File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 110, in start_kernel_for_session
kernel_id = yield maybe_future(
File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\tornado\gen.py", line 762, in run
value = future.result()
File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 176, in start_kernel
kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\jupyter_client\utils.py", line 25, in wrapped
return loop.run_until_complete(coro(*args, **kwargs))
File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
return f.result()
File "c:\users\honey\appdata\local\programs\python\python39\lib\asyncio\futures.py", line 201, in result
raise self._exception
File "c:\users\honey\appdata\local\programs\python\python39\lib\asyncio\tasks.py", line 256, in __step
result = coro.send(None)
File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\jupyter_client\multikernelmanager.py", line 186, in _async_start_kernel
self._add_kernel_when_ready(kernel_id, km, ensure_async(km.start_kernel(**kwargs)))
File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\jupyter_client\utils.py", line 25, in wrapped
return loop.run_until_complete(coro(*args, **kwargs))
File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
return f.result()
File "c:\users\honey\appdata\local\programs\python\python39\lib\asyncio\futures.py", line 201, in result
raise self._exception
File "c:\users\honey\appdata\local\programs\python\python39\lib\asyncio\tasks.py", line 256, in __step
result = coro.send(None)
File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\jupyter_client\manager.py", line 335, in _async_start_kernel
await ensure_async(self._launch_kernel(kernel_cmd, **kw))
File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\jupyter_client\utils.py", line 25, in wrapped
return loop.run_until_complete(coro(*args, **kwargs))
File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
return f.result()
File "c:\users\honey\appdata\local\programs\python\python39\lib\asyncio\futures.py", line 201, in result
raise self._exception
File "c:\users\honey\appdata\local\programs\python\python39\lib\asyncio\tasks.py", line 256, in __step
result = coro.send(None)
File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\jupyter_client\manager.py", line 257, in _async_launch_kernel
connection_info = await self.provisioner.launch_kernel(kernel_cmd, **kw)
File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\jupyter_client\provisioning\local_provisioner.py", line 179, in launch_kernel
self.process = launch_kernel(cmd, **scrubbed_kwargs)
File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\jupyter_client\launcher.py", line 169, in launch_kernel
raise ex
File "c:\users\honey\appdata\local\programs\python\python39\lib\site-packages\jupyter_client\launcher.py", line 157, in launch_kernel
proc = Popen(cmd, **kwargs)
File "c:\users\honey\appdata\local\programs\python\python39\lib\subprocess.py", line 947, in init
self._execute_child(args, executable, preexec_fn, close_fds,
File "c:\users\honey\appdata\local\programs\python\python39\lib\subprocess.py", line 1416, in _execute_child
hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
![Capture](https://user-images.githubusercontent.com/84119791/131222698-b6926e6e-c33e-4804-ab22-3d51da7f41e9.PNG)

**Comment by Hanok-Solomon-Vangepurapu** [comment]
Can any one please help me to solve this issue??? thanks in advance

**Comment by akabe** [comment]
I'm not sure that I can support you because I have not installed ocaml and ocaml-jupyter in windows ever.

I think cygwin cannot find /bin/sh required to launch ocaml-jupyter.
See `$(opam var share)/jupyter/kernel.json` for detail setting in your environment.
Maybe ocaml-jupyter works if you edit `"argv"` in kernel.json appropriately.

**Comment by Hanok-Solomon-Vangepurapu** [comment]
After runing this  command  $(opam var share)/jupyter/kernel.json 
 i got this 

Honey@LAPTOP-JA0VRAPS ~
$ $(opam var share)/jupyter/kernel.json
C:/OCaml64/home/Honey/.opam/4.10.1+mingw64/share/jupyter/kernel.json: line 2: display_name:: command not found
C:/OCaml64/home/Honey/.opam/4.10.1+mingw64/share/jupyter/kernel.json: line 3: language:: command not found
C:/OCaml64/home/Honey/.opam/4.10.1+mingw64/share/jupyter/kernel.json: line 4: argv:: command not found
C:/OCaml64/home/Honey/.opam/4.10.1+mingw64/share/jupyter/kernel.json: line 5: /bin/sh,: No such file or directory
C:/OCaml64/home/Honey/.opam/4.10.1+mingw64/share/jupyter/kernel.json: line 6: -c,: command not found
C:/OCaml64/home/Honey/.opam/4.10.1+mingw64/share/jupyter/kernel.json: line 7: eval OPAM_SWITCH_PREFIX='C:\\OCaml64\\home\\Honey\\.opam\\4.10.1+mingw64'; export OPAM_SWITCH_PREFIX;
OCAMLLIB='C:/OCaml64/home/Honey/.opam/4.10.1+mingw64/lib/ocaml'; export OCAMLLIB;
CC='x86_64-w64-mingw32-gcc.exe'; export CC;
CPP='x86_64-w64-mingw32-cpp.exe'; export CPP;
CAML_LD_LIBRARY_PATH='C:/OCaml64/home/Honey/.opam/4.10.1+mingw64/lib/stublibs;C:/OCaml64/home/Honey/.opam/4.10.1+mingw64/lib/ocaml/stublibs;C:/OCaml64/home/Honey/.opam/4.10.1+mingw64/lib/ocaml;C:/OCaml64/home/Honey/.opam/4.10.1+mingw64/lib/stublibs'; export CAML_LD_LIBRARY_PATH;
OCAML_TOPLEVEL_PATH='C:/OCaml64/home/Honey/.opam/4.10.1+mingw64/lib/toplevel'; export OCAML_TOPLEVEL_PATH;
PKG_CONFIG_PATH='C:/OCaml64/home/Honey/.opam/4.10.1+mingw64/lib/pkgconfig;C:/OCaml64/home/Honey/.opam/4.10.1+mingw64/lib/pkgconfig:'; export PKG_CONFIG_PATH;
PATH='/home/Honey/.opam/4.10.1+mingw64/bin:/usr/x86_64-w64-mingw32/sys-root/mingw/bin:/usr/local/bin:/usr/bin:/cygdrive/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/WINDOWS/System32/OpenSSH:/cygdrive/c/Users/Honey/AppData/Local/Programs/Python/Python39:/cygdrive/c/Program Files/Git/cmd:/cygdrive/c/Program Files/Docker/Docker/resources/bin:/cygdrive/c/ProgramData/DockerDesktop/version-bin:/:/cygdrive/c/Users/Honey/AppData/Local/Microsoft/WindowsApps:/cygdrive/c/Users/Honey/AppData/Local/Programs/Python/Python39/Scripts:/cygdrive/c/Program Files/JetBrains/PyCharm Community Edition 2020.3.3/bin'; export PATH; && C:/OCaml64/home/Honey/.opam/4.10.1+mingw64/bin/ocaml-jupyter-kernel "",: No such file or directory
C:/OCaml64/home/Honey/.opam/4.10.1+mingw64/share/jupyter/kernel.json: line 8: ocaml-jupyter-kernel,: command not found
C:/OCaml64/home/Honey/.opam/4.10.1+mingw64/share/jupyter/kernel.json: line 9: -init,: command not found
C:/OCaml64/home/Honey/.opam/4.10.1+mingw64/share/jupyter/kernel.json: line 10: --merlin,: command not found
C:/OCaml64/home/Honey/.opam/4.10.1+mingw64/share/jupyter/kernel.json: line 11: --verbosity,: command not found
C:/OCaml64/home/Honey/.opam/4.10.1+mingw64/share/jupyter/kernel.json: line 12: --connection-file,: command not found
C:/OCaml64/home/Honey/.opam/4.10.1+mingw64/share/jupyter/kernel.json: line 13: ]: command not found

**Comment by Hanok-Solomon-Vangepurapu** [comment]
can you explian this  statement "Maybe ocaml-jupyter works if you edit "argv" in kernel.json appropriately." i didnot  understand what your saying???

**Comment by akabe** [comment]
I don't recommend ocaml-jupyter in windows if you are not an expert of ocaml system for windows.
I think running ocaml-jupyter on windows is much difficult than running it on linux.

kernel.json is a JSON setting file, not an executable file. It contains information for calling ocaml-jupyter from jupyter. `"argv"` is an array of arguments passed to exec(3). From the following message, I guess that `argv` is inappropriate for you environment. However I don't know suitable argv.

```
proc = Popen(cmd, **kwargs)
File "c:\users\honey\appdata\local\programs\python\python39\lib\subprocess.py", line 947, in init
self._execute_child(args, executable, preexec_fn, close_fds,
File "c:\users\honey\appdata\local\programs\python\python39\lib\subprocess.py", line 1416, in _execute_child
hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by Hanok-Solomon-Vangepurapu** [comment]
The issue is resolved thanks for your help
